name: Simple Flask Application CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8
            pip install -r requirements.txt
      - name: Lint with flake8
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Unit Test
        run: |
            python -m unittest tests/unit_test.py
      - name: Integration Test
        run: |
            python -m unittest tests/integration.py

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker Build
        run: docker build -t simple-app-example .
      - name: Tags
        run: |
          docker tag simple-app-example ${{ secrets.DOCKER_HUB_USER }}/simple-app-example:${{ github.sha }}
          docker tag simple-app-example ${{ secrets.DOCKER_HUB_USER }}/simple-app-example:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/simple-app-example:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/simple-app-example:latest